name: Deploy to EC2

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Stop pm2
        run: |
          pm2 stop "splab-slack-bot"
      - name: Create .env file
        run: |
          touch .env
          echo SLACK_BOT_TOKEN=${{ secrets.SLACK_BOT_TOKEN }} >> .env
          echo SLACK_APP_TOKEN=${{ secrets.SLACK_APP_TOKEN }} >> .env
          echo IS_PRODUCTION=true >> .env
          echo TZ=Asia/Seoul >> .env
          echo SENDTIME_API_URL=https://api.sendtime.app >> .env
          echo SENDTIME_USER_ID=${{ secrets.SENDTIME_USER_ID }} >> .env
          echo SENDTIME_USER_PW=${{ secrets.SENDTIME_USER_PW }} >> .env
          echo REDIS_URL=${{ secrets.REDIS_URL }} >> .env
          echo GOOGLE_SERVICE_ACCOUNT_EMAIL=${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }} >> .env
          echo GOOGLE_SERVICE_ACCOUNT_KEY="\"${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}\"" >> .env
      - name: Install packages
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Start pm2
        run: |
          pm2 start dist/index.js --name "splab-slack-bot"
          pm2 save
